#!/bin/bash

# Chrome
USER_AGENT='Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.13 (KHTML, like Gecko) Chrome/24.0.1284.0 Safari/537.13'
CACHE_DIR=/tmp
SLEEP_SECS=10

#URL="${1-tycho.usno.navy.mil/cgi-bin/timer.pl}"
#META_MATCH='<html>'
#META_REPLACE='<html><head><meta http-equiv="refresh" content="10"><\/head>'

#URL="${1-whatsmy.browsersize.com/index.html}"

URL="${1-www.reddit.com/index.html}"

PAGE_PATH="$CACHE_DIR/wget-loop/data"
GET_CMD='wget'

CHROME=`which google-chrome chromium |head -n1`

get_page () {
    i=0
    DST=`readlink "$PAGE_PATH"`
    if [ -n "$DST" ]; then
        i="${DST: -1}"
        i=$((i?0:1))
    fi
    #echo "($DST) ($i)"

    rm -Rf "$PAGE_PATH$i" 
    "$GET_CMD" -H -k -K -p -q --user-agent="$USER_AGENT" --directory-prefix="$PAGE_PATH$i" "http://$URL"
    STATUS=$?
    if [ "$STATUS" = "0" ]; then
        ln -nfs "$PAGE_PATH$i" "$PAGE_PATH"
        if [ -n "$META_MATCH" -a -n "$META_REPLACE" ]; then
            sed -i.orig -e "s/$META_MATCH/$META_REPLACE/" "$PAGE_PATH/$URL"
        fi
    fi

    return "$STATUS"
}

CHROME_PID=''
while true; do
    if get_page; then
        if [ -z "$CHROME_PID" ]; then
            "$CHROME" --incognito --kiosk "file://$PAGE_PATH/$URL" &
            CHROME_PID="$!"
        fi
    fi
    sleep "$SLEEP_SECS"
done

exit
